// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WsMessageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Proto {

  /// <summary>Holder for reflection information generated from WsMessageId.proto</summary>
  public static partial class WsMessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for WsMessageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WsMessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFXc01lc3NhZ2VJZC5wcm90bxIHTmV0d29yayrGBQoLV3NNZXNzYWdlSWQS",
            "DwoLV1NfTVNHX05PTkUQABIWChJXU19DT05ORUNUX1JFUVVFU1QQZRIXChNX",
            "U19DT05ORUNUX1JFU1BPTlNFEGYSGAoUV1NfRElTQ09OTkVDVF9OT1RJRlkQ",
            "ZxILCgdXU19QSU5HEGgSCwoHV1NfUE9ORxBpEhMKD1dTX0FVVEhfUkVRVUVT",
            "VBBqEhQKEFdTX0FVVEhfUkVTUE9OU0UQaxITCg5XU19QVVNIX05PVElGWRDJ",
            "ARITCg5XU19NQUlMX05PVElGWRDKARIVChBXU19SRVdBUkRfTk9USUZZEMsB",
            "EhcKEldTX1NZU1RFTV9BTk5PVU5DRRDMARIVChBXU19GUklFTkRfT05MSU5F",
            "EM0BEhYKEVdTX0ZSSUVORF9PRkZMSU5FEM4BEhQKD1dTX0dVSUxEX05PVElG",
            "WRDPARIVChBXU19NQVRDSF9SRVFVRVNUEK0CEhQKD1dTX01BVENIX0NBTkNF",
            "TBCuAhIWChFXU19NQVRDSF9QUk9HUkVTUxCvAhIVChBXU19NQVRDSF9TVUND",
            "RVNTELACEhQKD1dTX01BVENIX0ZBSUxFRBCxAhIVChBXU19NQVRDSF9DT05G",
            "SVJNELICEhMKDldTX01BVENIX1JFQURZELMCEhMKDldTX1JBTktfVVBEQVRF",
            "EJEDEhYKEVdTX1JBTktfU1VCU0NSSUJFEJIDEhgKE1dTX1JBTktfVU5TVUJT",
            "Q1JJQkUQkwMSGgoVV1NfUkFOS19DSEFOR0VfTk9USUZZEJQDEhYKEVdTX0FD",
            "VElWSVRZX1NUQVJUEPUDEhQKD1dTX0FDVElWSVRZX0VORBD2AxIXChJXU19B",
            "Q1RJVklUWV9VUERBVEUQ9wMSFwoSV1NfQUNUSVZJVFlfUkVXQVJEEPgDEhYK",
            "EVdTX1JFRF9ET1RfVVBEQVRFEPkDQhCqAg1OZXR3b3JrLlByb3RvYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Network.Proto.WsMessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum WsMessageId {
    [pbr::OriginalName("WS_MSG_NONE")] WsMsgNone = 0,
    /// <summary>
    /// ========== 连接管理 (1xx) ==========
    /// </summary>
    [pbr::OriginalName("WS_CONNECT_REQUEST")] WsConnectRequest = 101,
    /// <summary>
    /// 连接响应
    /// </summary>
    [pbr::OriginalName("WS_CONNECT_RESPONSE")] WsConnectResponse = 102,
    /// <summary>
    /// 断开通知
    /// </summary>
    [pbr::OriginalName("WS_DISCONNECT_NOTIFY")] WsDisconnectNotify = 103,
    /// <summary>
    /// Ping
    /// </summary>
    [pbr::OriginalName("WS_PING")] WsPing = 104,
    /// <summary>
    /// Pong
    /// </summary>
    [pbr::OriginalName("WS_PONG")] WsPong = 105,
    /// <summary>
    /// 认证请求
    /// </summary>
    [pbr::OriginalName("WS_AUTH_REQUEST")] WsAuthRequest = 106,
    /// <summary>
    /// 认证响应
    /// </summary>
    [pbr::OriginalName("WS_AUTH_RESPONSE")] WsAuthResponse = 107,
    /// <summary>
    /// ========== 实时推送 (2xx) ==========
    /// </summary>
    [pbr::OriginalName("WS_PUSH_NOTIFY")] WsPushNotify = 201,
    /// <summary>
    /// 邮件通知
    /// </summary>
    [pbr::OriginalName("WS_MAIL_NOTIFY")] WsMailNotify = 202,
    /// <summary>
    /// 奖励通知
    /// </summary>
    [pbr::OriginalName("WS_REWARD_NOTIFY")] WsRewardNotify = 203,
    /// <summary>
    /// 系统公告
    /// </summary>
    [pbr::OriginalName("WS_SYSTEM_ANNOUNCE")] WsSystemAnnounce = 204,
    /// <summary>
    /// 好友上线通知
    /// </summary>
    [pbr::OriginalName("WS_FRIEND_ONLINE")] WsFriendOnline = 205,
    /// <summary>
    /// 好友下线通知
    /// </summary>
    [pbr::OriginalName("WS_FRIEND_OFFLINE")] WsFriendOffline = 206,
    /// <summary>
    /// 公会通知
    /// </summary>
    [pbr::OriginalName("WS_GUILD_NOTIFY")] WsGuildNotify = 207,
    /// <summary>
    /// ========== 匹配系统 (3xx) ==========
    /// </summary>
    [pbr::OriginalName("WS_MATCH_REQUEST")] WsMatchRequest = 301,
    /// <summary>
    /// 取消匹配
    /// </summary>
    [pbr::OriginalName("WS_MATCH_CANCEL")] WsMatchCancel = 302,
    /// <summary>
    /// 匹配进度
    /// </summary>
    [pbr::OriginalName("WS_MATCH_PROGRESS")] WsMatchProgress = 303,
    /// <summary>
    /// 匹配成功
    /// </summary>
    [pbr::OriginalName("WS_MATCH_SUCCESS")] WsMatchSuccess = 304,
    /// <summary>
    /// 匹配失败
    /// </summary>
    [pbr::OriginalName("WS_MATCH_FAILED")] WsMatchFailed = 305,
    /// <summary>
    /// 匹配确认
    /// </summary>
    [pbr::OriginalName("WS_MATCH_CONFIRM")] WsMatchConfirm = 306,
    /// <summary>
    /// 准备就绪
    /// </summary>
    [pbr::OriginalName("WS_MATCH_READY")] WsMatchReady = 307,
    /// <summary>
    /// ========== 排行榜 (4xx) ==========
    /// </summary>
    [pbr::OriginalName("WS_RANK_UPDATE")] WsRankUpdate = 401,
    /// <summary>
    /// 订阅排行榜
    /// </summary>
    [pbr::OriginalName("WS_RANK_SUBSCRIBE")] WsRankSubscribe = 402,
    /// <summary>
    /// 取消订阅
    /// </summary>
    [pbr::OriginalName("WS_RANK_UNSUBSCRIBE")] WsRankUnsubscribe = 403,
    /// <summary>
    /// 排名变化通知
    /// </summary>
    [pbr::OriginalName("WS_RANK_CHANGE_NOTIFY")] WsRankChangeNotify = 404,
    /// <summary>
    /// ========== 活动系统 (5xx) ==========
    /// </summary>
    [pbr::OriginalName("WS_ACTIVITY_START")] WsActivityStart = 501,
    /// <summary>
    /// 活动结束
    /// </summary>
    [pbr::OriginalName("WS_ACTIVITY_END")] WsActivityEnd = 502,
    /// <summary>
    /// 活动更新
    /// </summary>
    [pbr::OriginalName("WS_ACTIVITY_UPDATE")] WsActivityUpdate = 503,
    /// <summary>
    /// 活动奖励
    /// </summary>
    [pbr::OriginalName("WS_ACTIVITY_REWARD")] WsActivityReward = 504,
    /// <summary>
    /// 红点更新
    /// </summary>
    [pbr::OriginalName("WS_RED_DOT_UPDATE")] WsRedDotUpdate = 505,
  }

  #endregion

}

#endregion Designer generated code
