// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TcpMessageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Proto {

  /// <summary>Holder for reflection information generated from TcpMessageId.proto</summary>
  public static partial class TcpMessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for TcpMessageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TcpMessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJUY3BNZXNzYWdlSWQucHJvdG8SB05ldHdvcmsqwwkKDFRjcE1lc3NhZ2VJ",
            "ZBIQCgxUQ1BfTVNHX05PTkUQABIWChFUQ1BfTE9HSU5fUkVRVUVTVBDpBxIX",
            "ChJUQ1BfTE9HSU5fUkVTUE9OU0UQ6gcSGQoUVENQX1JFR0lTVEVSX1JFUVVF",
            "U1QQ6wcSGgoVVENQX1JFR0lTVEVSX1JFU1BPTlNFEOwHEhcKElRDUF9MT0dP",
            "VVRfUkVRVUVTVBDtBxIYChNUQ1BfTE9HT1VUX1JFU1BPTlNFEO4HEhoKFVRD",
            "UF9SRUNPTk5FQ1RfUkVRVUVTVBDvBxIbChZUQ1BfUkVDT05ORUNUX1JFU1BP",
            "TlNFEPAHEhQKD1RDUF9LSUNLX05PVElGWRDxBxIaChVUQ1BfSEVBUlRCRUFU",
            "X1JFUVVFU1QQ0Q8SGwoWVENQX0hFQVJUQkVBVF9SRVNQT05TRRDSDxIcChdU",
            "Q1BfRU5URVJfU0NFTkVfUkVRVUVTVBDTDxIdChhUQ1BfRU5URVJfU0NFTkVf",
            "UkVTUE9OU0UQ1A8SHAoXVENQX0xFQVZFX1NDRU5FX1JFUVVFU1QQ1Q8SHQoY",
            "VENQX0xFQVZFX1NDRU5FX1JFU1BPTlNFENYPEh8KGlRDUF9QTEFZRVJfRU5U",
            "RVJfQlJPQURDQVNUENcPEh8KGlRDUF9QTEFZRVJfTEVBVkVfQlJPQURDQVNU",
            "ENgPEhsKFlRDUF9TQ0VORV9JTkZPX1JFUVVFU1QQ2Q8SHAoXVENQX1NDRU5F",
            "X0lORk9fUkVTUE9OU0UQ2g8SGQoUVENQX0JBR19JTkZPX1JFUVVFU1QQuRcS",
            "GgoVVENQX0JBR19JTkZPX1JFU1BPTlNFELoXEhkKFFRDUF9VU0VfSVRFTV9S",
            "RVFVRVNUELsXEhoKFVRDUF9VU0VfSVRFTV9SRVNQT05TRRC8FxIaChVUQ1Bf",
            "RFJPUF9JVEVNX1JFUVVFU1QQvRcSGwoWVENQX0RST1BfSVRFTV9SRVNQT05T",
            "RRC+FxIbChZUQ1BfSVRFTV9DSEFOR0VfTk9USUZZEL8XEhUKEFRDUF9DSEFU",
            "X1JFUVVFU1QQoR8SFwoSVENQX0NIQVRfQlJPQURDQVNUEKIfEhwKF1RDUF9G",
            "UklFTkRfTElTVF9SRVFVRVNUEKMfEh0KGFRDUF9GUklFTkRfTElTVF9SRVNQ",
            "T05TRRCkHxIbChZUQ1BfQUREX0ZSSUVORF9SRVFVRVNUEKUfEhwKF1RDUF9B",
            "RERfRlJJRU5EX1JFU1BPTlNFEKYfEh4KGVRDUF9SRU1PVkVfRlJJRU5EX1JF",
            "UVVFU1QQpx8SHwoaVENQX1JFTU9WRV9GUklFTkRfUkVTUE9OU0UQqB8SFwoS",
            "VENQX0FUVEFDS19SRVFVRVNUEIknEhgKE1RDUF9BVFRBQ0tfUkVTUE9OU0UQ",
            "iicSFgoRVENQX0RBTUFHRV9OT1RJRlkQiycSFgoRVENQX1NLSUxMX1JFUVVF",
            "U1QQjCcSFwoSVENQX1NLSUxMX1JFU1BPTlNFEI0nEhQKD1RDUF9CVUZGX05P",
            "VElGWRCOJxIVChBUQ1BfREVBVEhfTk9USUZZEI8nEhcKElRDUF9SRVZJVkVf",
            "UkVRVUVTVBCQJxIYChNUQ1BfUkVWSVZFX1JFU1BPTlNFEJEnQhCqAg1OZXR3",
            "b3JrLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Network.Proto.TcpMessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TcpMessageId {
    [pbr::OriginalName("TCP_MSG_NONE")] TcpMsgNone = 0,
    /// <summary>
    /// ========== 登录模块 (1xxx) ==========
    /// </summary>
    [pbr::OriginalName("TCP_LOGIN_REQUEST")] TcpLoginRequest = 1001,
    [pbr::OriginalName("TCP_LOGIN_RESPONSE")] TcpLoginResponse = 1002,
    [pbr::OriginalName("TCP_REGISTER_REQUEST")] TcpRegisterRequest = 1003,
    [pbr::OriginalName("TCP_REGISTER_RESPONSE")] TcpRegisterResponse = 1004,
    [pbr::OriginalName("TCP_LOGOUT_REQUEST")] TcpLogoutRequest = 1005,
    [pbr::OriginalName("TCP_LOGOUT_RESPONSE")] TcpLogoutResponse = 1006,
    [pbr::OriginalName("TCP_RECONNECT_REQUEST")] TcpReconnectRequest = 1007,
    [pbr::OriginalName("TCP_RECONNECT_RESPONSE")] TcpReconnectResponse = 1008,
    [pbr::OriginalName("TCP_KICK_NOTIFY")] TcpKickNotify = 1009,
    /// <summary>
    /// ========== 游戏核心模块 (2xxx) ==========
    /// </summary>
    [pbr::OriginalName("TCP_HEARTBEAT_REQUEST")] TcpHeartbeatRequest = 2001,
    [pbr::OriginalName("TCP_HEARTBEAT_RESPONSE")] TcpHeartbeatResponse = 2002,
    [pbr::OriginalName("TCP_ENTER_SCENE_REQUEST")] TcpEnterSceneRequest = 2003,
    [pbr::OriginalName("TCP_ENTER_SCENE_RESPONSE")] TcpEnterSceneResponse = 2004,
    [pbr::OriginalName("TCP_LEAVE_SCENE_REQUEST")] TcpLeaveSceneRequest = 2005,
    [pbr::OriginalName("TCP_LEAVE_SCENE_RESPONSE")] TcpLeaveSceneResponse = 2006,
    [pbr::OriginalName("TCP_PLAYER_ENTER_BROADCAST")] TcpPlayerEnterBroadcast = 2007,
    [pbr::OriginalName("TCP_PLAYER_LEAVE_BROADCAST")] TcpPlayerLeaveBroadcast = 2008,
    [pbr::OriginalName("TCP_SCENE_INFO_REQUEST")] TcpSceneInfoRequest = 2009,
    [pbr::OriginalName("TCP_SCENE_INFO_RESPONSE")] TcpSceneInfoResponse = 2010,
    /// <summary>
    /// ========== 背包/道具模块 (3xxx) ==========
    /// </summary>
    [pbr::OriginalName("TCP_BAG_INFO_REQUEST")] TcpBagInfoRequest = 3001,
    [pbr::OriginalName("TCP_BAG_INFO_RESPONSE")] TcpBagInfoResponse = 3002,
    [pbr::OriginalName("TCP_USE_ITEM_REQUEST")] TcpUseItemRequest = 3003,
    [pbr::OriginalName("TCP_USE_ITEM_RESPONSE")] TcpUseItemResponse = 3004,
    [pbr::OriginalName("TCP_DROP_ITEM_REQUEST")] TcpDropItemRequest = 3005,
    [pbr::OriginalName("TCP_DROP_ITEM_RESPONSE")] TcpDropItemResponse = 3006,
    [pbr::OriginalName("TCP_ITEM_CHANGE_NOTIFY")] TcpItemChangeNotify = 3007,
    /// <summary>
    /// ========== 社交模块 (4xxx) ==========
    /// </summary>
    [pbr::OriginalName("TCP_CHAT_REQUEST")] TcpChatRequest = 4001,
    [pbr::OriginalName("TCP_CHAT_BROADCAST")] TcpChatBroadcast = 4002,
    [pbr::OriginalName("TCP_FRIEND_LIST_REQUEST")] TcpFriendListRequest = 4003,
    [pbr::OriginalName("TCP_FRIEND_LIST_RESPONSE")] TcpFriendListResponse = 4004,
    [pbr::OriginalName("TCP_ADD_FRIEND_REQUEST")] TcpAddFriendRequest = 4005,
    [pbr::OriginalName("TCP_ADD_FRIEND_RESPONSE")] TcpAddFriendResponse = 4006,
    [pbr::OriginalName("TCP_REMOVE_FRIEND_REQUEST")] TcpRemoveFriendRequest = 4007,
    [pbr::OriginalName("TCP_REMOVE_FRIEND_RESPONSE")] TcpRemoveFriendResponse = 4008,
    /// <summary>
    /// ========== 战斗模块 (5xxx) ==========
    /// </summary>
    [pbr::OriginalName("TCP_ATTACK_REQUEST")] TcpAttackRequest = 5001,
    [pbr::OriginalName("TCP_ATTACK_RESPONSE")] TcpAttackResponse = 5002,
    [pbr::OriginalName("TCP_DAMAGE_NOTIFY")] TcpDamageNotify = 5003,
    [pbr::OriginalName("TCP_SKILL_REQUEST")] TcpSkillRequest = 5004,
    [pbr::OriginalName("TCP_SKILL_RESPONSE")] TcpSkillResponse = 5005,
    [pbr::OriginalName("TCP_BUFF_NOTIFY")] TcpBuffNotify = 5006,
    [pbr::OriginalName("TCP_DEATH_NOTIFY")] TcpDeathNotify = 5007,
    [pbr::OriginalName("TCP_REVIVE_REQUEST")] TcpReviveRequest = 5008,
    [pbr::OriginalName("TCP_REVIVE_RESPONSE")] TcpReviveResponse = 5009,
  }

  #endregion

}

#endregion Designer generated code
