
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace XHFramework.Game
{
public sealed partial class TableLocalizationText : Luban.BeanBase
{
    public TableLocalizationText(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        CN = _buf.ReadString();
        EN = _buf.ReadString();
    }

    public static TableLocalizationText DeserializeTableLocalizationText(ByteBuf _buf)
    {
        return new TableLocalizationText(_buf);
    }

    /// <summary>
    /// 语言编号
    /// </summary>
    public readonly int Id;
    public readonly string Key;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string CN;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string EN;
   
    public const int __ID__ = 2045443892;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "key:" + Key + ","
        + "CN:" + CN + ","
        + "EN:" + EN + ","
        + "}";
    }
}
}

