
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace XHFramework.Game
{
public partial class Tables
{
    public TbEntity TbEntity {get; }
    public TbLocalizationText TbLocalizationText {get; }
    public TbMap TbMap {get; }
    public TbMusic TbMusic {get; }
    public TbRole TbRole {get; }
    public TbScene TbScene {get; }
    public TbSound TbSound {get; }
    public TbUISound TbUISound {get; }

    public Tables()
    {
    }
}

}

