
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbEntity : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableEntity> _dataMap;
    private readonly System.Collections.Generic.List<TableEntity> _dataList;

    public TbEntity()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableEntity>();
        _dataList = new System.Collections.Generic.List<TableEntity>();
    }

    public System.Collections.Generic.Dictionary<int, TableEntity> DataMap => _dataMap;
    public System.Collections.Generic.List<TableEntity> DataList => _dataList;

    public TableEntity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableEntity Get(int key) => _dataMap[key];
    public TableEntity this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableEntity _v;
            _v = global::XHFramework.Game.TableEntity.DeserializeTableEntity(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

