
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbLocalizationText : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableLocalizationText> _dataMap;
    private readonly System.Collections.Generic.List<TableLocalizationText> _dataList;

    public TbLocalizationText()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableLocalizationText>();
        _dataList = new System.Collections.Generic.List<TableLocalizationText>();
    }

    public System.Collections.Generic.Dictionary<int, TableLocalizationText> DataMap => _dataMap;
    public System.Collections.Generic.List<TableLocalizationText> DataList => _dataList;

    public TableLocalizationText GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableLocalizationText Get(int key) => _dataMap[key];
    public TableLocalizationText this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableLocalizationText _v;
            _v = global::XHFramework.Game.TableLocalizationText.DeserializeTableLocalizationText(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

