
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbMap : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableMap> _dataMap;
    private readonly System.Collections.Generic.List<TableMap> _dataList;

    public TbMap()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableMap>();
        _dataList = new System.Collections.Generic.List<TableMap>();
    }

    public System.Collections.Generic.Dictionary<int, TableMap> DataMap => _dataMap;
    public System.Collections.Generic.List<TableMap> DataList => _dataList;

    public TableMap GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableMap Get(int key) => _dataMap[key];
    public TableMap this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableMap _v;
            _v = global::XHFramework.Game.TableMap.DeserializeTableMap(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

