
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbMusic : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableMusic> _dataMap;
    private readonly System.Collections.Generic.List<TableMusic> _dataList;

    public TbMusic()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableMusic>();
        _dataList = new System.Collections.Generic.List<TableMusic>();
    }

    public System.Collections.Generic.Dictionary<int, TableMusic> DataMap => _dataMap;
    public System.Collections.Generic.List<TableMusic> DataList => _dataList;

    public TableMusic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableMusic Get(int key) => _dataMap[key];
    public TableMusic this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableMusic _v;
            _v = global::XHFramework.Game.TableMusic.DeserializeTableMusic(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

