
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbRole : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableRole> _dataMap;
    private readonly System.Collections.Generic.List<TableRole> _dataList;

    public TbRole()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableRole>();
        _dataList = new System.Collections.Generic.List<TableRole>();
    }

    public System.Collections.Generic.Dictionary<int, TableRole> DataMap => _dataMap;
    public System.Collections.Generic.List<TableRole> DataList => _dataList;

    public TableRole GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableRole Get(int key) => _dataMap[key];
    public TableRole this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableRole _v;
            _v = global::XHFramework.Game.TableRole.DeserializeTableRole(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

