
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbScene : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableScene> _dataMap;
    private readonly System.Collections.Generic.List<TableScene> _dataList;

    public TbScene()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableScene>();
        _dataList = new System.Collections.Generic.List<TableScene>();
    }

    public System.Collections.Generic.Dictionary<int, TableScene> DataMap => _dataMap;
    public System.Collections.Generic.List<TableScene> DataList => _dataList;

    public TableScene GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableScene Get(int key) => _dataMap[key];
    public TableScene this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableScene _v;
            _v = global::XHFramework.Game.TableScene.DeserializeTableScene(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

