
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using XHFramework.Core;


namespace XHFramework.Game
{
public partial class TbSound : TableBase
{
    private readonly System.Collections.Generic.Dictionary<int, TableSound> _dataMap;
    private readonly System.Collections.Generic.List<TableSound> _dataList;

    public TbSound()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TableSound>();
        _dataList = new System.Collections.Generic.List<TableSound>();
    }

    public System.Collections.Generic.Dictionary<int, TableSound> DataMap => _dataMap;
    public System.Collections.Generic.List<TableSound> DataList => _dataList;

    public TableSound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableSound Get(int key) => _dataMap[key];
    public TableSound this[int key] => _dataMap[key];

    public void LoadData(ByteBuf _buf)
    {
        for (int n = _buf.ReadSize(); n > 0; --n)
        {
            TableSound _v;
            _v = global::XHFramework.Game.TableSound.DeserializeTableSound(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public void Cleardata()
    {
        _dataList?.Clear();
        _dataMap?.Clear();
    }

}

}

