// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CombatSync.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Proto {

  /// <summary>Holder for reflection information generated from CombatSync.proto</summary>
  public static partial class CombatSyncReflection {

    #region Descriptor
    /// <summary>File descriptor for CombatSync.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CombatSyncReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBDb21iYXRTeW5jLnByb3RvEgdOZXR3b3JrGg9VZHBDb21tb24ucHJvdG8i",
            "8gEKCkF0dGFja1N5bmMSIgoGaGVhZGVyGAEgASgLMhIuTmV0d29yay5VZHBI",
            "ZWFkZXISEwoLYXR0YWNrZXJfaWQYAiABKAMSEQoJdGFyZ2V0X2lkGAMgASgD",
            "EhEKCWF0dGFja19pZBgEIAEoBRIsCg9hdHRhY2tfcG9zaXRpb24YBSABKAsy",
            "Ey5OZXR3b3JrLlVkcFZlY3RvcjMSLQoQYXR0YWNrX2RpcmVjdGlvbhgGIAEo",
            "CzITLk5ldHdvcmsuVWRwVmVjdG9yMxITCgthdHRhY2tfdHlwZRgHIAEoBRIT",
            "CgthdHRhY2tfdGltZRgIIAEoAyLuAQoKSGl0Q29uZmlybRIiCgZoZWFkZXIY",
            "ASABKAsyEi5OZXR3b3JrLlVkcEhlYWRlchITCgthdHRhY2tlcl9pZBgCIAEo",
            "AxIRCgl0YXJnZXRfaWQYAyABKAMSEQoJYXR0YWNrX2lkGAQgASgFEg4KBmlz",
            "X2hpdBgFIAEoCBIOCgZkYW1hZ2UYBiABKAUSJgoJaGl0X3BvaW50GAcgASgL",
            "MhMuTmV0d29yay5VZHBWZWN0b3IzEicKCmhpdF9ub3JtYWwYCCABKAsyEy5O",
            "ZXR3b3JrLlVkcFZlY3RvcjMSEAoIaGl0X3R5cGUYCSABKAUikwIKDlByb2pl",
            "Y3RpbGVTeW5jEiIKBmhlYWRlchgBIAEoCzISLk5ldHdvcmsuVWRwSGVhZGVy",
            "EhUKDXByb2plY3RpbGVfaWQYAiABKAMSEAoIb3duZXJfaWQYAyABKAMSFwoP",
            "cHJvamVjdGlsZV90eXBlGAQgASgFEiUKCHBvc2l0aW9uGAUgASgLMhMuTmV0",
            "d29yay5VZHBWZWN0b3IzEiUKCHZlbG9jaXR5GAYgASgLMhMuTmV0d29yay5V",
            "ZHBWZWN0b3IzEigKCHJvdGF0aW9uGAcgASgLMhYuTmV0d29yay5VZHBRdWF0",
            "ZXJuaW9uEhAKCGxpZmV0aW1lGAggASgCEhEKCXRhcmdldF9pZBgJIAEoAyLW",
            "AQoHQW9lU3luYxIiCgZoZWFkZXIYASABKAsyEi5OZXR3b3JrLlVkcEhlYWRl",
            "chIOCgZhb2VfaWQYAiABKAMSEQoJY2FzdGVyX2lkGAMgASgDEhAKCGFvZV90",
            "eXBlGAQgASgFEiMKBmNlbnRlchgFIAEoCzITLk5ldHdvcmsuVWRwVmVjdG9y",
            "MxIOCgZyYWRpdXMYBiABKAISEAoIZHVyYXRpb24YByABKAISFQoNdGlja19p",
            "bnRlcnZhbBgIIAEoBRIUCgxhZmZlY3RlZF9pZHMYCSADKAMitQEKC0NvbWJh",
            "dEV2ZW50EiIKBmhlYWRlchgBIAEoCzISLk5ldHdvcmsuVWRwSGVhZGVyEhIK",
            "CmV2ZW50X3R5cGUYAiABKAUSEQoJc291cmNlX2lkGAMgASgDEhEKCXRhcmdl",
            "dF9pZBgEIAEoAxIlCghwb3NpdGlvbhgFIAEoCzITLk5ldHdvcmsuVWRwVmVj",
            "dG9yMxINCgV2YWx1ZRgGIAEoBRISCgpleHRyYV9kYXRhGAcgASgMQhCqAg1O",
            "ZXR3b3JrLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Network.Proto.UdpCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.AttackSync), global::Network.Proto.AttackSync.Parser, new[]{ "Header", "AttackerId", "TargetId", "AttackId", "AttackPosition", "AttackDirection", "AttackType", "AttackTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.HitConfirm), global::Network.Proto.HitConfirm.Parser, new[]{ "Header", "AttackerId", "TargetId", "AttackId", "IsHit", "Damage", "HitPoint", "HitNormal", "HitType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.ProjectileSync), global::Network.Proto.ProjectileSync.Parser, new[]{ "Header", "ProjectileId", "OwnerId", "ProjectileType", "Position", "Velocity", "Rotation", "Lifetime", "TargetId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.AoeSync), global::Network.Proto.AoeSync.Parser, new[]{ "Header", "AoeId", "CasterId", "AoeType", "Center", "Radius", "Duration", "TickInterval", "AffectedIds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.CombatEvent), global::Network.Proto.CombatEvent.Parser, new[]{ "Header", "EventType", "SourceId", "TargetId", "Position", "Value", "ExtraData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 攻击同步（实时战斗）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AttackSync : pb::IMessage<AttackSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AttackSync> _parser = new pb::MessageParser<AttackSync>(() => new AttackSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AttackSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.CombatSyncReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttackSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttackSync(AttackSync other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      attackerId_ = other.attackerId_;
      targetId_ = other.targetId_;
      attackId_ = other.attackId_;
      attackPosition_ = other.attackPosition_ != null ? other.attackPosition_.Clone() : null;
      attackDirection_ = other.attackDirection_ != null ? other.attackDirection_.Clone() : null;
      attackType_ = other.attackType_;
      attackTime_ = other.attackTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AttackSync Clone() {
      return new AttackSync(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "attacker_id" field.</summary>
    public const int AttackerIdFieldNumber = 2;
    private long attackerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AttackerId {
      get { return attackerId_; }
      set {
        attackerId_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 3;
    private long targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "attack_id" field.</summary>
    public const int AttackIdFieldNumber = 4;
    private int attackId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackId {
      get { return attackId_; }
      set {
        attackId_ = value;
      }
    }

    /// <summary>Field number for the "attack_position" field.</summary>
    public const int AttackPositionFieldNumber = 5;
    private global::Network.Proto.UdpVector3 attackPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 AttackPosition {
      get { return attackPosition_; }
      set {
        attackPosition_ = value;
      }
    }

    /// <summary>Field number for the "attack_direction" field.</summary>
    public const int AttackDirectionFieldNumber = 6;
    private global::Network.Proto.UdpVector3 attackDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 AttackDirection {
      get { return attackDirection_; }
      set {
        attackDirection_ = value;
      }
    }

    /// <summary>Field number for the "attack_type" field.</summary>
    public const int AttackTypeFieldNumber = 7;
    private int attackType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackType {
      get { return attackType_; }
      set {
        attackType_ = value;
      }
    }

    /// <summary>Field number for the "attack_time" field.</summary>
    public const int AttackTimeFieldNumber = 8;
    private long attackTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AttackTime {
      get { return attackTime_; }
      set {
        attackTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AttackSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AttackSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (AttackerId != other.AttackerId) return false;
      if (TargetId != other.TargetId) return false;
      if (AttackId != other.AttackId) return false;
      if (!object.Equals(AttackPosition, other.AttackPosition)) return false;
      if (!object.Equals(AttackDirection, other.AttackDirection)) return false;
      if (AttackType != other.AttackType) return false;
      if (AttackTime != other.AttackTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (AttackerId != 0L) hash ^= AttackerId.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (AttackId != 0) hash ^= AttackId.GetHashCode();
      if (attackPosition_ != null) hash ^= AttackPosition.GetHashCode();
      if (attackDirection_ != null) hash ^= AttackDirection.GetHashCode();
      if (AttackType != 0) hash ^= AttackType.GetHashCode();
      if (AttackTime != 0L) hash ^= AttackTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (AttackerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AttackerId);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetId);
      }
      if (AttackId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AttackId);
      }
      if (attackPosition_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(AttackPosition);
      }
      if (attackDirection_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(AttackDirection);
      }
      if (AttackType != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(AttackType);
      }
      if (AttackTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(AttackTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (AttackerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AttackerId);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetId);
      }
      if (AttackId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AttackId);
      }
      if (attackPosition_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(AttackPosition);
      }
      if (attackDirection_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(AttackDirection);
      }
      if (AttackType != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(AttackType);
      }
      if (AttackTime != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(AttackTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (AttackerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AttackerId);
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (AttackId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackId);
      }
      if (attackPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttackPosition);
      }
      if (attackDirection_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AttackDirection);
      }
      if (AttackType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackType);
      }
      if (AttackTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AttackTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AttackSync other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.AttackerId != 0L) {
        AttackerId = other.AttackerId;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.AttackId != 0) {
        AttackId = other.AttackId;
      }
      if (other.attackPosition_ != null) {
        if (attackPosition_ == null) {
          AttackPosition = new global::Network.Proto.UdpVector3();
        }
        AttackPosition.MergeFrom(other.AttackPosition);
      }
      if (other.attackDirection_ != null) {
        if (attackDirection_ == null) {
          AttackDirection = new global::Network.Proto.UdpVector3();
        }
        AttackDirection.MergeFrom(other.AttackDirection);
      }
      if (other.AttackType != 0) {
        AttackType = other.AttackType;
      }
      if (other.AttackTime != 0L) {
        AttackTime = other.AttackTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            AttackerId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadInt64();
            break;
          }
          case 32: {
            AttackId = input.ReadInt32();
            break;
          }
          case 42: {
            if (attackPosition_ == null) {
              AttackPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(AttackPosition);
            break;
          }
          case 50: {
            if (attackDirection_ == null) {
              AttackDirection = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(AttackDirection);
            break;
          }
          case 56: {
            AttackType = input.ReadInt32();
            break;
          }
          case 64: {
            AttackTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            AttackerId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadInt64();
            break;
          }
          case 32: {
            AttackId = input.ReadInt32();
            break;
          }
          case 42: {
            if (attackPosition_ == null) {
              AttackPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(AttackPosition);
            break;
          }
          case 50: {
            if (attackDirection_ == null) {
              AttackDirection = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(AttackDirection);
            break;
          }
          case 56: {
            AttackType = input.ReadInt32();
            break;
          }
          case 64: {
            AttackTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 命中确认
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HitConfirm : pb::IMessage<HitConfirm>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HitConfirm> _parser = new pb::MessageParser<HitConfirm>(() => new HitConfirm());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HitConfirm> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.CombatSyncReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HitConfirm() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HitConfirm(HitConfirm other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      attackerId_ = other.attackerId_;
      targetId_ = other.targetId_;
      attackId_ = other.attackId_;
      isHit_ = other.isHit_;
      damage_ = other.damage_;
      hitPoint_ = other.hitPoint_ != null ? other.hitPoint_.Clone() : null;
      hitNormal_ = other.hitNormal_ != null ? other.hitNormal_.Clone() : null;
      hitType_ = other.hitType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HitConfirm Clone() {
      return new HitConfirm(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "attacker_id" field.</summary>
    public const int AttackerIdFieldNumber = 2;
    private long attackerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AttackerId {
      get { return attackerId_; }
      set {
        attackerId_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 3;
    private long targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "attack_id" field.</summary>
    public const int AttackIdFieldNumber = 4;
    private int attackId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackId {
      get { return attackId_; }
      set {
        attackId_ = value;
      }
    }

    /// <summary>Field number for the "is_hit" field.</summary>
    public const int IsHitFieldNumber = 5;
    private bool isHit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsHit {
      get { return isHit_; }
      set {
        isHit_ = value;
      }
    }

    /// <summary>Field number for the "damage" field.</summary>
    public const int DamageFieldNumber = 6;
    private int damage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Damage {
      get { return damage_; }
      set {
        damage_ = value;
      }
    }

    /// <summary>Field number for the "hit_point" field.</summary>
    public const int HitPointFieldNumber = 7;
    private global::Network.Proto.UdpVector3 hitPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 HitPoint {
      get { return hitPoint_; }
      set {
        hitPoint_ = value;
      }
    }

    /// <summary>Field number for the "hit_normal" field.</summary>
    public const int HitNormalFieldNumber = 8;
    private global::Network.Proto.UdpVector3 hitNormal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 HitNormal {
      get { return hitNormal_; }
      set {
        hitNormal_ = value;
      }
    }

    /// <summary>Field number for the "hit_type" field.</summary>
    public const int HitTypeFieldNumber = 9;
    private int hitType_;
    /// <summary>
    /// 0: normal, 1: critical, 2: block, 3: dodge
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int HitType {
      get { return hitType_; }
      set {
        hitType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HitConfirm);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HitConfirm other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (AttackerId != other.AttackerId) return false;
      if (TargetId != other.TargetId) return false;
      if (AttackId != other.AttackId) return false;
      if (IsHit != other.IsHit) return false;
      if (Damage != other.Damage) return false;
      if (!object.Equals(HitPoint, other.HitPoint)) return false;
      if (!object.Equals(HitNormal, other.HitNormal)) return false;
      if (HitType != other.HitType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (AttackerId != 0L) hash ^= AttackerId.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (AttackId != 0) hash ^= AttackId.GetHashCode();
      if (IsHit != false) hash ^= IsHit.GetHashCode();
      if (Damage != 0) hash ^= Damage.GetHashCode();
      if (hitPoint_ != null) hash ^= HitPoint.GetHashCode();
      if (hitNormal_ != null) hash ^= HitNormal.GetHashCode();
      if (HitType != 0) hash ^= HitType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (AttackerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AttackerId);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetId);
      }
      if (AttackId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AttackId);
      }
      if (IsHit != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsHit);
      }
      if (Damage != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Damage);
      }
      if (hitPoint_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HitPoint);
      }
      if (hitNormal_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(HitNormal);
      }
      if (HitType != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(HitType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (AttackerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AttackerId);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TargetId);
      }
      if (AttackId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AttackId);
      }
      if (IsHit != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsHit);
      }
      if (Damage != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Damage);
      }
      if (hitPoint_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HitPoint);
      }
      if (hitNormal_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(HitNormal);
      }
      if (HitType != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(HitType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (AttackerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AttackerId);
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (AttackId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackId);
      }
      if (IsHit != false) {
        size += 1 + 1;
      }
      if (Damage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Damage);
      }
      if (hitPoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HitPoint);
      }
      if (hitNormal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HitNormal);
      }
      if (HitType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HitType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HitConfirm other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.AttackerId != 0L) {
        AttackerId = other.AttackerId;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.AttackId != 0) {
        AttackId = other.AttackId;
      }
      if (other.IsHit != false) {
        IsHit = other.IsHit;
      }
      if (other.Damage != 0) {
        Damage = other.Damage;
      }
      if (other.hitPoint_ != null) {
        if (hitPoint_ == null) {
          HitPoint = new global::Network.Proto.UdpVector3();
        }
        HitPoint.MergeFrom(other.HitPoint);
      }
      if (other.hitNormal_ != null) {
        if (hitNormal_ == null) {
          HitNormal = new global::Network.Proto.UdpVector3();
        }
        HitNormal.MergeFrom(other.HitNormal);
      }
      if (other.HitType != 0) {
        HitType = other.HitType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            AttackerId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadInt64();
            break;
          }
          case 32: {
            AttackId = input.ReadInt32();
            break;
          }
          case 40: {
            IsHit = input.ReadBool();
            break;
          }
          case 48: {
            Damage = input.ReadInt32();
            break;
          }
          case 58: {
            if (hitPoint_ == null) {
              HitPoint = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(HitPoint);
            break;
          }
          case 66: {
            if (hitNormal_ == null) {
              HitNormal = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(HitNormal);
            break;
          }
          case 72: {
            HitType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            AttackerId = input.ReadInt64();
            break;
          }
          case 24: {
            TargetId = input.ReadInt64();
            break;
          }
          case 32: {
            AttackId = input.ReadInt32();
            break;
          }
          case 40: {
            IsHit = input.ReadBool();
            break;
          }
          case 48: {
            Damage = input.ReadInt32();
            break;
          }
          case 58: {
            if (hitPoint_ == null) {
              HitPoint = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(HitPoint);
            break;
          }
          case 66: {
            if (hitNormal_ == null) {
              HitNormal = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(HitNormal);
            break;
          }
          case 72: {
            HitType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 弹道同步
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ProjectileSync : pb::IMessage<ProjectileSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProjectileSync> _parser = new pb::MessageParser<ProjectileSync>(() => new ProjectileSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProjectileSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.CombatSyncReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectileSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectileSync(ProjectileSync other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      projectileId_ = other.projectileId_;
      ownerId_ = other.ownerId_;
      projectileType_ = other.projectileType_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      lifetime_ = other.lifetime_;
      targetId_ = other.targetId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProjectileSync Clone() {
      return new ProjectileSync(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "projectile_id" field.</summary>
    public const int ProjectileIdFieldNumber = 2;
    private long projectileId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ProjectileId {
      get { return projectileId_; }
      set {
        projectileId_ = value;
      }
    }

    /// <summary>Field number for the "owner_id" field.</summary>
    public const int OwnerIdFieldNumber = 3;
    private long ownerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OwnerId {
      get { return ownerId_; }
      set {
        ownerId_ = value;
      }
    }

    /// <summary>Field number for the "projectile_type" field.</summary>
    public const int ProjectileTypeFieldNumber = 4;
    private int projectileType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProjectileType {
      get { return projectileType_; }
      set {
        projectileType_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 5;
    private global::Network.Proto.UdpVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 6;
    private global::Network.Proto.UdpVector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 7;
    private global::Network.Proto.UdpQuaternion rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpQuaternion Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "lifetime" field.</summary>
    public const int LifetimeFieldNumber = 8;
    private float lifetime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Lifetime {
      get { return lifetime_; }
      set {
        lifetime_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 9;
    private long targetId_;
    /// <summary>
    /// 追踪目标（可选）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProjectileSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProjectileSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (ProjectileId != other.ProjectileId) return false;
      if (OwnerId != other.OwnerId) return false;
      if (ProjectileType != other.ProjectileType) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Lifetime, other.Lifetime)) return false;
      if (TargetId != other.TargetId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (ProjectileId != 0L) hash ^= ProjectileId.GetHashCode();
      if (OwnerId != 0L) hash ^= OwnerId.GetHashCode();
      if (ProjectileType != 0) hash ^= ProjectileType.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (Lifetime != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Lifetime);
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (ProjectileId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProjectileId);
      }
      if (OwnerId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(OwnerId);
      }
      if (ProjectileType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ProjectileType);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (velocity_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Velocity);
      }
      if (rotation_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Rotation);
      }
      if (Lifetime != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Lifetime);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TargetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (ProjectileId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProjectileId);
      }
      if (OwnerId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(OwnerId);
      }
      if (ProjectileType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ProjectileType);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (velocity_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Velocity);
      }
      if (rotation_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Rotation);
      }
      if (Lifetime != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Lifetime);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TargetId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (ProjectileId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProjectileId);
      }
      if (OwnerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OwnerId);
      }
      if (ProjectileType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProjectileType);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (Lifetime != 0F) {
        size += 1 + 4;
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProjectileSync other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.ProjectileId != 0L) {
        ProjectileId = other.ProjectileId;
      }
      if (other.OwnerId != 0L) {
        OwnerId = other.OwnerId;
      }
      if (other.ProjectileType != 0) {
        ProjectileType = other.ProjectileType;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Network.Proto.UdpVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Network.Proto.UdpVector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::Network.Proto.UdpQuaternion();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.Lifetime != 0F) {
        Lifetime = other.Lifetime;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            ProjectileId = input.ReadInt64();
            break;
          }
          case 24: {
            OwnerId = input.ReadInt64();
            break;
          }
          case 32: {
            ProjectileType = input.ReadInt32();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 50: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 58: {
            if (rotation_ == null) {
              Rotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 69: {
            Lifetime = input.ReadFloat();
            break;
          }
          case 72: {
            TargetId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            ProjectileId = input.ReadInt64();
            break;
          }
          case 24: {
            OwnerId = input.ReadInt64();
            break;
          }
          case 32: {
            ProjectileType = input.ReadInt32();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 50: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 58: {
            if (rotation_ == null) {
              Rotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 69: {
            Lifetime = input.ReadFloat();
            break;
          }
          case 72: {
            TargetId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// AOE同步
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AoeSync : pb::IMessage<AoeSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AoeSync> _parser = new pb::MessageParser<AoeSync>(() => new AoeSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AoeSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.CombatSyncReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AoeSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AoeSync(AoeSync other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      aoeId_ = other.aoeId_;
      casterId_ = other.casterId_;
      aoeType_ = other.aoeType_;
      center_ = other.center_ != null ? other.center_.Clone() : null;
      radius_ = other.radius_;
      duration_ = other.duration_;
      tickInterval_ = other.tickInterval_;
      affectedIds_ = other.affectedIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AoeSync Clone() {
      return new AoeSync(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "aoe_id" field.</summary>
    public const int AoeIdFieldNumber = 2;
    private long aoeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AoeId {
      get { return aoeId_; }
      set {
        aoeId_ = value;
      }
    }

    /// <summary>Field number for the "caster_id" field.</summary>
    public const int CasterIdFieldNumber = 3;
    private long casterId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CasterId {
      get { return casterId_; }
      set {
        casterId_ = value;
      }
    }

    /// <summary>Field number for the "aoe_type" field.</summary>
    public const int AoeTypeFieldNumber = 4;
    private int aoeType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AoeType {
      get { return aoeType_; }
      set {
        aoeType_ = value;
      }
    }

    /// <summary>Field number for the "center" field.</summary>
    public const int CenterFieldNumber = 5;
    private global::Network.Proto.UdpVector3 center_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Center {
      get { return center_; }
      set {
        center_ = value;
      }
    }

    /// <summary>Field number for the "radius" field.</summary>
    public const int RadiusFieldNumber = 6;
    private float radius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Radius {
      get { return radius_; }
      set {
        radius_ = value;
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 7;
    private float duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    /// <summary>Field number for the "tick_interval" field.</summary>
    public const int TickIntervalFieldNumber = 8;
    private int tickInterval_;
    /// <summary>
    /// 伤害间隔（毫秒）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TickInterval {
      get { return tickInterval_; }
      set {
        tickInterval_ = value;
      }
    }

    /// <summary>Field number for the "affected_ids" field.</summary>
    public const int AffectedIdsFieldNumber = 9;
    private static readonly pb::FieldCodec<long> _repeated_affectedIds_codec
        = pb::FieldCodec.ForInt64(74);
    private readonly pbc::RepeatedField<long> affectedIds_ = new pbc::RepeatedField<long>();
    /// <summary>
    /// 受影响的实体ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> AffectedIds {
      get { return affectedIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AoeSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AoeSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (AoeId != other.AoeId) return false;
      if (CasterId != other.CasterId) return false;
      if (AoeType != other.AoeType) return false;
      if (!object.Equals(Center, other.Center)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Radius, other.Radius)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Duration, other.Duration)) return false;
      if (TickInterval != other.TickInterval) return false;
      if(!affectedIds_.Equals(other.affectedIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (AoeId != 0L) hash ^= AoeId.GetHashCode();
      if (CasterId != 0L) hash ^= CasterId.GetHashCode();
      if (AoeType != 0) hash ^= AoeType.GetHashCode();
      if (center_ != null) hash ^= Center.GetHashCode();
      if (Radius != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Radius);
      if (Duration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Duration);
      if (TickInterval != 0) hash ^= TickInterval.GetHashCode();
      hash ^= affectedIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (AoeId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AoeId);
      }
      if (CasterId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CasterId);
      }
      if (AoeType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AoeType);
      }
      if (center_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Center);
      }
      if (Radius != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Radius);
      }
      if (Duration != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Duration);
      }
      if (TickInterval != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(TickInterval);
      }
      affectedIds_.WriteTo(output, _repeated_affectedIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (AoeId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AoeId);
      }
      if (CasterId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CasterId);
      }
      if (AoeType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(AoeType);
      }
      if (center_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Center);
      }
      if (Radius != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(Radius);
      }
      if (Duration != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(Duration);
      }
      if (TickInterval != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(TickInterval);
      }
      affectedIds_.WriteTo(ref output, _repeated_affectedIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (AoeId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AoeId);
      }
      if (CasterId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CasterId);
      }
      if (AoeType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AoeType);
      }
      if (center_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Center);
      }
      if (Radius != 0F) {
        size += 1 + 4;
      }
      if (Duration != 0F) {
        size += 1 + 4;
      }
      if (TickInterval != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TickInterval);
      }
      size += affectedIds_.CalculateSize(_repeated_affectedIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AoeSync other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.AoeId != 0L) {
        AoeId = other.AoeId;
      }
      if (other.CasterId != 0L) {
        CasterId = other.CasterId;
      }
      if (other.AoeType != 0) {
        AoeType = other.AoeType;
      }
      if (other.center_ != null) {
        if (center_ == null) {
          Center = new global::Network.Proto.UdpVector3();
        }
        Center.MergeFrom(other.Center);
      }
      if (other.Radius != 0F) {
        Radius = other.Radius;
      }
      if (other.Duration != 0F) {
        Duration = other.Duration;
      }
      if (other.TickInterval != 0) {
        TickInterval = other.TickInterval;
      }
      affectedIds_.Add(other.affectedIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            AoeId = input.ReadInt64();
            break;
          }
          case 24: {
            CasterId = input.ReadInt64();
            break;
          }
          case 32: {
            AoeType = input.ReadInt32();
            break;
          }
          case 42: {
            if (center_ == null) {
              Center = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Center);
            break;
          }
          case 53: {
            Radius = input.ReadFloat();
            break;
          }
          case 61: {
            Duration = input.ReadFloat();
            break;
          }
          case 64: {
            TickInterval = input.ReadInt32();
            break;
          }
          case 74:
          case 72: {
            affectedIds_.AddEntriesFrom(input, _repeated_affectedIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            AoeId = input.ReadInt64();
            break;
          }
          case 24: {
            CasterId = input.ReadInt64();
            break;
          }
          case 32: {
            AoeType = input.ReadInt32();
            break;
          }
          case 42: {
            if (center_ == null) {
              Center = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Center);
            break;
          }
          case 53: {
            Radius = input.ReadFloat();
            break;
          }
          case 61: {
            Duration = input.ReadFloat();
            break;
          }
          case 64: {
            TickInterval = input.ReadInt32();
            break;
          }
          case 74:
          case 72: {
            affectedIds_.AddEntriesFrom(ref input, _repeated_affectedIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 战斗事件（通用战斗事件同步）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CombatEvent : pb::IMessage<CombatEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CombatEvent> _parser = new pb::MessageParser<CombatEvent>(() => new CombatEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CombatEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.CombatSyncReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombatEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombatEvent(CombatEvent other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      eventType_ = other.eventType_;
      sourceId_ = other.sourceId_;
      targetId_ = other.targetId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      value_ = other.value_;
      extraData_ = other.extraData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CombatEvent Clone() {
      return new CombatEvent(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 2;
    private int eventType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "source_id" field.</summary>
    public const int SourceIdFieldNumber = 3;
    private long sourceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SourceId {
      get { return sourceId_; }
      set {
        sourceId_ = value;
      }
    }

    /// <summary>Field number for the "target_id" field.</summary>
    public const int TargetIdFieldNumber = 4;
    private long targetId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 5;
    private global::Network.Proto.UdpVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 6;
    private int value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "extra_data" field.</summary>
    public const int ExtraDataFieldNumber = 7;
    private pb::ByteString extraData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ExtraData {
      get { return extraData_; }
      set {
        extraData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CombatEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CombatEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (EventType != other.EventType) return false;
      if (SourceId != other.SourceId) return false;
      if (TargetId != other.TargetId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (Value != other.Value) return false;
      if (ExtraData != other.ExtraData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (EventType != 0) hash ^= EventType.GetHashCode();
      if (SourceId != 0L) hash ^= SourceId.GetHashCode();
      if (TargetId != 0L) hash ^= TargetId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (ExtraData.Length != 0) hash ^= ExtraData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (EventType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EventType);
      }
      if (SourceId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SourceId);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TargetId);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (Value != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Value);
      }
      if (ExtraData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(ExtraData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (EventType != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EventType);
      }
      if (SourceId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SourceId);
      }
      if (TargetId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TargetId);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (Value != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Value);
      }
      if (ExtraData.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(ExtraData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (EventType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventType);
      }
      if (SourceId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SourceId);
      }
      if (TargetId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TargetId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (ExtraData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ExtraData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CombatEvent other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.EventType != 0) {
        EventType = other.EventType;
      }
      if (other.SourceId != 0L) {
        SourceId = other.SourceId;
      }
      if (other.TargetId != 0L) {
        TargetId = other.TargetId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Network.Proto.UdpVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      if (other.ExtraData.Length != 0) {
        ExtraData = other.ExtraData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            EventType = input.ReadInt32();
            break;
          }
          case 24: {
            SourceId = input.ReadInt64();
            break;
          }
          case 32: {
            TargetId = input.ReadInt64();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 48: {
            Value = input.ReadInt32();
            break;
          }
          case 58: {
            ExtraData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            EventType = input.ReadInt32();
            break;
          }
          case 24: {
            SourceId = input.ReadInt64();
            break;
          }
          case 32: {
            TargetId = input.ReadInt64();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 48: {
            Value = input.ReadInt32();
            break;
          }
          case 58: {
            ExtraData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
