// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Movement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Proto {

  /// <summary>Holder for reflection information generated from Movement.proto</summary>
  public static partial class MovementReflection {

    #region Descriptor
    /// <summary>File descriptor for Movement.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MovementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Nb3ZlbWVudC5wcm90bxIHTmV0d29yaxoPVWRwQ29tbW9uLnByb3RvIvQB",
            "CghNb3ZlU3luYxIiCgZoZWFkZXIYASABKAsyEi5OZXR3b3JrLlVkcEhlYWRl",
            "chIPCgd1c2VyX2lkGAIgASgDEiUKCHBvc2l0aW9uGAMgASgLMhMuTmV0d29y",
            "ay5VZHBWZWN0b3IzEigKCHJvdGF0aW9uGAQgASgLMhYuTmV0d29yay5VZHBR",
            "dWF0ZXJuaW9uEiUKCHZlbG9jaXR5GAUgASgLMhMuTmV0d29yay5VZHBWZWN0",
            "b3IzEhMKC2lucHV0X2ZsYWdzGAYgASgNEhIKCm1vdmVfc3BlZWQYByABKAIS",
            "EgoKbW92ZV9zdGF0ZRgIIAEoBSLTAQoQTW92ZUJyb2FkY2FzdFVkcBIiCgZo",
            "ZWFkZXIYASABKAsyEi5OZXR3b3JrLlVkcEhlYWRlchIPCgd1c2VyX2lkGAIg",
            "ASgDEiUKCHBvc2l0aW9uGAMgASgLMhMuTmV0d29yay5VZHBWZWN0b3IzEigK",
            "CHJvdGF0aW9uGAQgASgLMhYuTmV0d29yay5VZHBRdWF0ZXJuaW9uEiUKCHZl",
            "bG9jaXR5GAUgASgLMhMuTmV0d29yay5VZHBWZWN0b3IzEhIKCm1vdmVfc3Rh",
            "dGUYBiABKAUi0wEKD1Bvc2l0aW9uQ29ycmVjdBIiCgZoZWFkZXIYASABKAsy",
            "Ei5OZXR3b3JrLlVkcEhlYWRlchIPCgd1c2VyX2lkGAIgASgDEi0KEGNvcnJl",
            "Y3RfcG9zaXRpb24YAyABKAsyEy5OZXR3b3JrLlVkcFZlY3RvcjMSMAoQY29y",
            "cmVjdF9yb3RhdGlvbhgEIAEoCzIWLk5ldHdvcmsuVWRwUXVhdGVybmlvbhIa",
            "ChJjb3JyZWN0ZWRfc2VxdWVuY2UYBSABKA0SDgoGcmVhc29uGAYgASgJIrsB",
            "Cg5UZWxlcG9ydE5vdGlmeRIiCgZoZWFkZXIYASABKAsyEi5OZXR3b3JrLlVk",
            "cEhlYWRlchIPCgd1c2VyX2lkGAIgASgDEiwKD3RhcmdldF9wb3NpdGlvbhgD",
            "IAEoCzITLk5ldHdvcmsuVWRwVmVjdG9yMxIvCg90YXJnZXRfcm90YXRpb24Y",
            "BCABKAsyFi5OZXR3b3JrLlVkcFF1YXRlcm5pb24SFQoNdGVsZXBvcnRfdHlw",
            "ZRgFIAEoBSK7AQoISnVtcFN5bmMSIgoGaGVhZGVyGAEgASgLMhIuTmV0d29y",
            "ay5VZHBIZWFkZXISDwoHdXNlcl9pZBgCIAEoAxIrCg5zdGFydF9wb3NpdGlv",
            "bhgDIAEoCzITLk5ldHdvcmsuVWRwVmVjdG9yMxIlCgh2ZWxvY2l0eRgEIAEo",
            "CzITLk5ldHdvcmsuVWRwVmVjdG9yMxISCgpqdW1wX2ZvcmNlGAUgASgCEhIK",
            "Cmp1bXBfY291bnQYBiABKAUiqAEKDFZlbG9jaXR5U3luYxIiCgZoZWFkZXIY",
            "ASABKAsyEi5OZXR3b3JrLlVkcEhlYWRlchIPCgd1c2VyX2lkGAIgASgDEiUK",
            "CHZlbG9jaXR5GAMgASgLMhMuTmV0d29yay5VZHBWZWN0b3IzEikKDGFjY2Vs",
            "ZXJhdGlvbhgEIAEoCzITLk5ldHdvcmsuVWRwVmVjdG9yMxIRCgltYXhfc3Bl",
            "ZWQYBSABKAJCEKoCDU5ldHdvcmsuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Network.Proto.UdpCommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.MoveSync), global::Network.Proto.MoveSync.Parser, new[]{ "Header", "UserId", "Position", "Rotation", "Velocity", "InputFlags", "MoveSpeed", "MoveState" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.MoveBroadcastUdp), global::Network.Proto.MoveBroadcastUdp.Parser, new[]{ "Header", "UserId", "Position", "Rotation", "Velocity", "MoveState" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.PositionCorrect), global::Network.Proto.PositionCorrect.Parser, new[]{ "Header", "UserId", "CorrectPosition", "CorrectRotation", "CorrectedSequence", "Reason" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.TeleportNotify), global::Network.Proto.TeleportNotify.Parser, new[]{ "Header", "UserId", "TargetPosition", "TargetRotation", "TeleportType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.JumpSync), global::Network.Proto.JumpSync.Parser, new[]{ "Header", "UserId", "StartPosition", "Velocity", "JumpForce", "JumpCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Network.Proto.VelocitySync), global::Network.Proto.VelocitySync.Parser, new[]{ "Header", "UserId", "Velocity", "Acceleration", "MaxSpeed" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 移动同步（客户端 -> 服务器）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MoveSync : pb::IMessage<MoveSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveSync> _parser = new pb::MessageParser<MoveSync>(() => new MoveSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.MovementReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveSync(MoveSync other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      userId_ = other.userId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      inputFlags_ = other.inputFlags_;
      moveSpeed_ = other.moveSpeed_;
      moveState_ = other.moveState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveSync Clone() {
      return new MoveSync(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Network.Proto.UdpVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 4;
    private global::Network.Proto.UdpQuaternion rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpQuaternion Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 5;
    private global::Network.Proto.UdpVector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "input_flags" field.</summary>
    public const int InputFlagsFieldNumber = 6;
    private uint inputFlags_;
    /// <summary>
    /// 输入标志位：W/A/S/D/Jump/Sprint等
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint InputFlags {
      get { return inputFlags_; }
      set {
        inputFlags_ = value;
      }
    }

    /// <summary>Field number for the "move_speed" field.</summary>
    public const int MoveSpeedFieldNumber = 7;
    private float moveSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MoveSpeed {
      get { return moveSpeed_; }
      set {
        moveSpeed_ = value;
      }
    }

    /// <summary>Field number for the "move_state" field.</summary>
    public const int MoveStateFieldNumber = 8;
    private int moveState_;
    /// <summary>
    /// 0: idle, 1: walk, 2: run, 3: sprint, 4: jump, 5: fall
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MoveState {
      get { return moveState_; }
      set {
        moveState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (InputFlags != other.InputFlags) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MoveSpeed, other.MoveSpeed)) return false;
      if (MoveState != other.MoveState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (InputFlags != 0) hash ^= InputFlags.GetHashCode();
      if (MoveSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MoveSpeed);
      if (MoveState != 0) hash ^= MoveState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (rotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Rotation);
      }
      if (velocity_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Velocity);
      }
      if (InputFlags != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(InputFlags);
      }
      if (MoveSpeed != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(MoveSpeed);
      }
      if (MoveState != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MoveState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (rotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Rotation);
      }
      if (velocity_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Velocity);
      }
      if (InputFlags != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(InputFlags);
      }
      if (MoveSpeed != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(MoveSpeed);
      }
      if (MoveState != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(MoveState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (InputFlags != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InputFlags);
      }
      if (MoveSpeed != 0F) {
        size += 1 + 4;
      }
      if (MoveState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MoveState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveSync other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Network.Proto.UdpVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::Network.Proto.UdpQuaternion();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Network.Proto.UdpVector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.InputFlags != 0) {
        InputFlags = other.InputFlags;
      }
      if (other.MoveSpeed != 0F) {
        MoveSpeed = other.MoveSpeed;
      }
      if (other.MoveState != 0) {
        MoveState = other.MoveState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (rotation_ == null) {
              Rotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 42: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 48: {
            InputFlags = input.ReadUInt32();
            break;
          }
          case 61: {
            MoveSpeed = input.ReadFloat();
            break;
          }
          case 64: {
            MoveState = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (rotation_ == null) {
              Rotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 42: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 48: {
            InputFlags = input.ReadUInt32();
            break;
          }
          case 61: {
            MoveSpeed = input.ReadFloat();
            break;
          }
          case 64: {
            MoveState = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 移动广播（服务器 -> 客户端）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MoveBroadcastUdp : pb::IMessage<MoveBroadcastUdp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveBroadcastUdp> _parser = new pb::MessageParser<MoveBroadcastUdp>(() => new MoveBroadcastUdp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveBroadcastUdp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.MovementReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveBroadcastUdp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveBroadcastUdp(MoveBroadcastUdp other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      userId_ = other.userId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      moveState_ = other.moveState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveBroadcastUdp Clone() {
      return new MoveBroadcastUdp(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::Network.Proto.UdpVector3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 4;
    private global::Network.Proto.UdpQuaternion rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpQuaternion Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 5;
    private global::Network.Proto.UdpVector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "move_state" field.</summary>
    public const int MoveStateFieldNumber = 6;
    private int moveState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MoveState {
      get { return moveState_; }
      set {
        moveState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveBroadcastUdp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveBroadcastUdp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (MoveState != other.MoveState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (MoveState != 0) hash ^= MoveState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (rotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Rotation);
      }
      if (velocity_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Velocity);
      }
      if (MoveState != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MoveState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (rotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Rotation);
      }
      if (velocity_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Velocity);
      }
      if (MoveState != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MoveState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (MoveState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MoveState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveBroadcastUdp other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Network.Proto.UdpVector3();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::Network.Proto.UdpQuaternion();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Network.Proto.UdpVector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.MoveState != 0) {
        MoveState = other.MoveState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (rotation_ == null) {
              Rotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 42: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 48: {
            MoveState = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (rotation_ == null) {
              Rotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(Rotation);
            break;
          }
          case 42: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 48: {
            MoveState = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 位置校正（服务器 -> 客户端）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PositionCorrect : pb::IMessage<PositionCorrect>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PositionCorrect> _parser = new pb::MessageParser<PositionCorrect>(() => new PositionCorrect());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PositionCorrect> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.MovementReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PositionCorrect() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PositionCorrect(PositionCorrect other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      userId_ = other.userId_;
      correctPosition_ = other.correctPosition_ != null ? other.correctPosition_.Clone() : null;
      correctRotation_ = other.correctRotation_ != null ? other.correctRotation_.Clone() : null;
      correctedSequence_ = other.correctedSequence_;
      reason_ = other.reason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PositionCorrect Clone() {
      return new PositionCorrect(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "correct_position" field.</summary>
    public const int CorrectPositionFieldNumber = 3;
    private global::Network.Proto.UdpVector3 correctPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 CorrectPosition {
      get { return correctPosition_; }
      set {
        correctPosition_ = value;
      }
    }

    /// <summary>Field number for the "correct_rotation" field.</summary>
    public const int CorrectRotationFieldNumber = 4;
    private global::Network.Proto.UdpQuaternion correctRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpQuaternion CorrectRotation {
      get { return correctRotation_; }
      set {
        correctRotation_ = value;
      }
    }

    /// <summary>Field number for the "corrected_sequence" field.</summary>
    public const int CorrectedSequenceFieldNumber = 5;
    private uint correctedSequence_;
    /// <summary>
    /// 被校正的输入序列号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CorrectedSequence {
      get { return correctedSequence_; }
      set {
        correctedSequence_ = value;
      }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 6;
    private string reason_ = "";
    /// <summary>
    /// 校正原因
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Reason {
      get { return reason_; }
      set {
        reason_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PositionCorrect);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PositionCorrect other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(CorrectPosition, other.CorrectPosition)) return false;
      if (!object.Equals(CorrectRotation, other.CorrectRotation)) return false;
      if (CorrectedSequence != other.CorrectedSequence) return false;
      if (Reason != other.Reason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (correctPosition_ != null) hash ^= CorrectPosition.GetHashCode();
      if (correctRotation_ != null) hash ^= CorrectRotation.GetHashCode();
      if (CorrectedSequence != 0) hash ^= CorrectedSequence.GetHashCode();
      if (Reason.Length != 0) hash ^= Reason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (correctPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CorrectPosition);
      }
      if (correctRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CorrectRotation);
      }
      if (CorrectedSequence != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CorrectedSequence);
      }
      if (Reason.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (correctPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CorrectPosition);
      }
      if (correctRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CorrectRotation);
      }
      if (CorrectedSequence != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CorrectedSequence);
      }
      if (Reason.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Reason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (correctPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CorrectPosition);
      }
      if (correctRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CorrectRotation);
      }
      if (CorrectedSequence != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CorrectedSequence);
      }
      if (Reason.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PositionCorrect other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.correctPosition_ != null) {
        if (correctPosition_ == null) {
          CorrectPosition = new global::Network.Proto.UdpVector3();
        }
        CorrectPosition.MergeFrom(other.CorrectPosition);
      }
      if (other.correctRotation_ != null) {
        if (correctRotation_ == null) {
          CorrectRotation = new global::Network.Proto.UdpQuaternion();
        }
        CorrectRotation.MergeFrom(other.CorrectRotation);
      }
      if (other.CorrectedSequence != 0) {
        CorrectedSequence = other.CorrectedSequence;
      }
      if (other.Reason.Length != 0) {
        Reason = other.Reason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (correctPosition_ == null) {
              CorrectPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(CorrectPosition);
            break;
          }
          case 34: {
            if (correctRotation_ == null) {
              CorrectRotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(CorrectRotation);
            break;
          }
          case 40: {
            CorrectedSequence = input.ReadUInt32();
            break;
          }
          case 50: {
            Reason = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (correctPosition_ == null) {
              CorrectPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(CorrectPosition);
            break;
          }
          case 34: {
            if (correctRotation_ == null) {
              CorrectRotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(CorrectRotation);
            break;
          }
          case 40: {
            CorrectedSequence = input.ReadUInt32();
            break;
          }
          case 50: {
            Reason = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 瞬移通知
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TeleportNotify : pb::IMessage<TeleportNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TeleportNotify> _parser = new pb::MessageParser<TeleportNotify>(() => new TeleportNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TeleportNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.MovementReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeleportNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeleportNotify(TeleportNotify other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      userId_ = other.userId_;
      targetPosition_ = other.targetPosition_ != null ? other.targetPosition_.Clone() : null;
      targetRotation_ = other.targetRotation_ != null ? other.targetRotation_.Clone() : null;
      teleportType_ = other.teleportType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TeleportNotify Clone() {
      return new TeleportNotify(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "target_position" field.</summary>
    public const int TargetPositionFieldNumber = 3;
    private global::Network.Proto.UdpVector3 targetPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 TargetPosition {
      get { return targetPosition_; }
      set {
        targetPosition_ = value;
      }
    }

    /// <summary>Field number for the "target_rotation" field.</summary>
    public const int TargetRotationFieldNumber = 4;
    private global::Network.Proto.UdpQuaternion targetRotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpQuaternion TargetRotation {
      get { return targetRotation_; }
      set {
        targetRotation_ = value;
      }
    }

    /// <summary>Field number for the "teleport_type" field.</summary>
    public const int TeleportTypeFieldNumber = 5;
    private int teleportType_;
    /// <summary>
    /// 0: 技能, 1: 传送点, 2: GM命令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TeleportType {
      get { return teleportType_; }
      set {
        teleportType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TeleportNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TeleportNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(TargetPosition, other.TargetPosition)) return false;
      if (!object.Equals(TargetRotation, other.TargetRotation)) return false;
      if (TeleportType != other.TeleportType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (targetPosition_ != null) hash ^= TargetPosition.GetHashCode();
      if (targetRotation_ != null) hash ^= TargetRotation.GetHashCode();
      if (TeleportType != 0) hash ^= TeleportType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (targetPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TargetPosition);
      }
      if (targetRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TargetRotation);
      }
      if (TeleportType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TeleportType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (targetPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TargetPosition);
      }
      if (targetRotation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TargetRotation);
      }
      if (TeleportType != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TeleportType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (targetPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetPosition);
      }
      if (targetRotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetRotation);
      }
      if (TeleportType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TeleportType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TeleportNotify other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.targetPosition_ != null) {
        if (targetPosition_ == null) {
          TargetPosition = new global::Network.Proto.UdpVector3();
        }
        TargetPosition.MergeFrom(other.TargetPosition);
      }
      if (other.targetRotation_ != null) {
        if (targetRotation_ == null) {
          TargetRotation = new global::Network.Proto.UdpQuaternion();
        }
        TargetRotation.MergeFrom(other.TargetRotation);
      }
      if (other.TeleportType != 0) {
        TeleportType = other.TeleportType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (targetPosition_ == null) {
              TargetPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(TargetPosition);
            break;
          }
          case 34: {
            if (targetRotation_ == null) {
              TargetRotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(TargetRotation);
            break;
          }
          case 40: {
            TeleportType = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (targetPosition_ == null) {
              TargetPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(TargetPosition);
            break;
          }
          case 34: {
            if (targetRotation_ == null) {
              TargetRotation = new global::Network.Proto.UdpQuaternion();
            }
            input.ReadMessage(TargetRotation);
            break;
          }
          case 40: {
            TeleportType = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 跳跃同步
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class JumpSync : pb::IMessage<JumpSync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JumpSync> _parser = new pb::MessageParser<JumpSync>(() => new JumpSync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JumpSync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.MovementReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JumpSync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JumpSync(JumpSync other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      userId_ = other.userId_;
      startPosition_ = other.startPosition_ != null ? other.startPosition_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      jumpForce_ = other.jumpForce_;
      jumpCount_ = other.jumpCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JumpSync Clone() {
      return new JumpSync(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "start_position" field.</summary>
    public const int StartPositionFieldNumber = 3;
    private global::Network.Proto.UdpVector3 startPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 StartPosition {
      get { return startPosition_; }
      set {
        startPosition_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 4;
    private global::Network.Proto.UdpVector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "jump_force" field.</summary>
    public const int JumpForceFieldNumber = 5;
    private float jumpForce_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float JumpForce {
      get { return jumpForce_; }
      set {
        jumpForce_ = value;
      }
    }

    /// <summary>Field number for the "jump_count" field.</summary>
    public const int JumpCountFieldNumber = 6;
    private int jumpCount_;
    /// <summary>
    /// 跳跃次数（用于多段跳）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int JumpCount {
      get { return jumpCount_; }
      set {
        jumpCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JumpSync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JumpSync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(StartPosition, other.StartPosition)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(JumpForce, other.JumpForce)) return false;
      if (JumpCount != other.JumpCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (startPosition_ != null) hash ^= StartPosition.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (JumpForce != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(JumpForce);
      if (JumpCount != 0) hash ^= JumpCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (startPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(StartPosition);
      }
      if (velocity_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Velocity);
      }
      if (JumpForce != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(JumpForce);
      }
      if (JumpCount != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(JumpCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (startPosition_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(StartPosition);
      }
      if (velocity_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Velocity);
      }
      if (JumpForce != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(JumpForce);
      }
      if (JumpCount != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(JumpCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (startPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartPosition);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (JumpForce != 0F) {
        size += 1 + 4;
      }
      if (JumpCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(JumpCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JumpSync other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.startPosition_ != null) {
        if (startPosition_ == null) {
          StartPosition = new global::Network.Proto.UdpVector3();
        }
        StartPosition.MergeFrom(other.StartPosition);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Network.Proto.UdpVector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.JumpForce != 0F) {
        JumpForce = other.JumpForce;
      }
      if (other.JumpCount != 0) {
        JumpCount = other.JumpCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (startPosition_ == null) {
              StartPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(StartPosition);
            break;
          }
          case 34: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 45: {
            JumpForce = input.ReadFloat();
            break;
          }
          case 48: {
            JumpCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (startPosition_ == null) {
              StartPosition = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(StartPosition);
            break;
          }
          case 34: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 45: {
            JumpForce = input.ReadFloat();
            break;
          }
          case 48: {
            JumpCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 速度同步
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VelocitySync : pb::IMessage<VelocitySync>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VelocitySync> _parser = new pb::MessageParser<VelocitySync>(() => new VelocitySync());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VelocitySync> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Network.Proto.MovementReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VelocitySync() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VelocitySync(VelocitySync other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      userId_ = other.userId_;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      acceleration_ = other.acceleration_ != null ? other.acceleration_.Clone() : null;
      maxSpeed_ = other.maxSpeed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VelocitySync Clone() {
      return new VelocitySync(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Network.Proto.UdpHeader header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpHeader Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 2;
    private long userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 3;
    private global::Network.Proto.UdpVector3 velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "acceleration" field.</summary>
    public const int AccelerationFieldNumber = 4;
    private global::Network.Proto.UdpVector3 acceleration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Network.Proto.UdpVector3 Acceleration {
      get { return acceleration_; }
      set {
        acceleration_ = value;
      }
    }

    /// <summary>Field number for the "max_speed" field.</summary>
    public const int MaxSpeedFieldNumber = 5;
    private float maxSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxSpeed {
      get { return maxSpeed_; }
      set {
        maxSpeed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VelocitySync);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VelocitySync other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (UserId != other.UserId) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!object.Equals(Acceleration, other.Acceleration)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxSpeed, other.MaxSpeed)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (UserId != 0L) hash ^= UserId.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (acceleration_ != null) hash ^= Acceleration.GetHashCode();
      if (MaxSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxSpeed);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (velocity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Velocity);
      }
      if (acceleration_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Acceleration);
      }
      if (MaxSpeed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxSpeed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (UserId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(UserId);
      }
      if (velocity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Velocity);
      }
      if (acceleration_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Acceleration);
      }
      if (MaxSpeed != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxSpeed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (UserId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserId);
      }
      if (velocity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (acceleration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Acceleration);
      }
      if (MaxSpeed != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VelocitySync other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Network.Proto.UdpHeader();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.UserId != 0L) {
        UserId = other.UserId;
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Network.Proto.UdpVector3();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.acceleration_ != null) {
        if (acceleration_ == null) {
          Acceleration = new global::Network.Proto.UdpVector3();
        }
        Acceleration.MergeFrom(other.Acceleration);
      }
      if (other.MaxSpeed != 0F) {
        MaxSpeed = other.MaxSpeed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 34: {
            if (acceleration_ == null) {
              Acceleration = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Acceleration);
            break;
          }
          case 45: {
            MaxSpeed = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Network.Proto.UdpHeader();
            }
            input.ReadMessage(Header);
            break;
          }
          case 16: {
            UserId = input.ReadInt64();
            break;
          }
          case 26: {
            if (velocity_ == null) {
              Velocity = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 34: {
            if (acceleration_ == null) {
              Acceleration = new global::Network.Proto.UdpVector3();
            }
            input.ReadMessage(Acceleration);
            break;
          }
          case 45: {
            MaxSpeed = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
