// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UdpMessageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Network.Proto {

  /// <summary>Holder for reflection information generated from UdpMessageId.proto</summary>
  public static partial class UdpMessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for UdpMessageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UdpMessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJVZHBNZXNzYWdlSWQucHJvdG8SB05ldHdvcmsq2QMKDFVkcE1lc3NhZ2VJ",
            "ZBIQCgxVRFBfTVNHX05PTkUQABIRCg1VRFBfTU9WRV9TWU5DEGUSFgoSVURQ",
            "X01PVkVfQlJPQURDQVNUEGYSGAoUVURQX1BPU0lUSU9OX0NPUlJFQ1QQZxIX",
            "ChNVRFBfVEVMRVBPUlRfTk9USUZZEGgSEQoNVURQX0pVTVBfU1lOQxBpEhUK",
            "EVVEUF9WRUxPQ0lUWV9TWU5DEGoSEwoOVURQX1NUQVRFX1NZTkMQyQESGAoT",
            "VURQX1NUQVRFX0JST0FEQ0FTVBDKARIXChJVRFBfQU5JTUFUSU9OX1NZTkMQ",
            "ywESGwoWVURQX1RSQU5TRk9STV9TTkFQU0hPVBDMARIbChZVRFBfSU5URVJQ",
            "T0xBVElPTl9EQVRBEM0BEhQKD1VEUF9BVFRBQ0tfU1lOQxCtAhIUCg9VRFBf",
            "SElUX0NPTkZJUk0QrgISGAoTVURQX1BST0pFQ1RJTEVfU1lOQxCvAhIRCgxV",
            "RFBfQU9FX1NZTkMQsAISFQoQVURQX0NPTUJBVF9FVkVOVBCxAhITCg5VRFBf",
            "Vk9JQ0VfREFUQRCRAxIUCg9VRFBfVk9JQ0VfU1RBUlQQkgMSEgoNVURQX1ZP",
            "SUNFX0VORBCTA0IQqgINTmV0d29yay5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Network.Proto.UdpMessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum UdpMessageId {
    [pbr::OriginalName("UDP_MSG_NONE")] UdpMsgNone = 0,
    /// <summary>
    /// ========== 移动同步 (1xx) ==========
    /// </summary>
    [pbr::OriginalName("UDP_MOVE_SYNC")] UdpMoveSync = 101,
    /// <summary>
    /// 移动广播
    /// </summary>
    [pbr::OriginalName("UDP_MOVE_BROADCAST")] UdpMoveBroadcast = 102,
    /// <summary>
    /// 位置校正
    /// </summary>
    [pbr::OriginalName("UDP_POSITION_CORRECT")] UdpPositionCorrect = 103,
    /// <summary>
    /// 瞬移通知
    /// </summary>
    [pbr::OriginalName("UDP_TELEPORT_NOTIFY")] UdpTeleportNotify = 104,
    /// <summary>
    /// 跳跃同步
    /// </summary>
    [pbr::OriginalName("UDP_JUMP_SYNC")] UdpJumpSync = 105,
    /// <summary>
    /// 速度同步
    /// </summary>
    [pbr::OriginalName("UDP_VELOCITY_SYNC")] UdpVelocitySync = 106,
    /// <summary>
    /// ========== 状态同步 (2xx) ==========
    /// </summary>
    [pbr::OriginalName("UDP_STATE_SYNC")] UdpStateSync = 201,
    /// <summary>
    /// 状态广播
    /// </summary>
    [pbr::OriginalName("UDP_STATE_BROADCAST")] UdpStateBroadcast = 202,
    /// <summary>
    /// 动画同步
    /// </summary>
    [pbr::OriginalName("UDP_ANIMATION_SYNC")] UdpAnimationSync = 203,
    /// <summary>
    /// Transform快照
    /// </summary>
    [pbr::OriginalName("UDP_TRANSFORM_SNAPSHOT")] UdpTransformSnapshot = 204,
    /// <summary>
    /// 插值数据
    /// </summary>
    [pbr::OriginalName("UDP_INTERPOLATION_DATA")] UdpInterpolationData = 205,
    /// <summary>
    /// ========== 战斗同步 (3xx) ==========
    /// </summary>
    [pbr::OriginalName("UDP_ATTACK_SYNC")] UdpAttackSync = 301,
    /// <summary>
    /// 命中确认
    /// </summary>
    [pbr::OriginalName("UDP_HIT_CONFIRM")] UdpHitConfirm = 302,
    /// <summary>
    /// 弹道同步
    /// </summary>
    [pbr::OriginalName("UDP_PROJECTILE_SYNC")] UdpProjectileSync = 303,
    /// <summary>
    /// AOE同步
    /// </summary>
    [pbr::OriginalName("UDP_AOE_SYNC")] UdpAoeSync = 304,
    /// <summary>
    /// 战斗事件
    /// </summary>
    [pbr::OriginalName("UDP_COMBAT_EVENT")] UdpCombatEvent = 305,
    /// <summary>
    /// ========== 语音/视频 (4xx) ==========
    /// </summary>
    [pbr::OriginalName("UDP_VOICE_DATA")] UdpVoiceData = 401,
    /// <summary>
    /// 开始语音
    /// </summary>
    [pbr::OriginalName("UDP_VOICE_START")] UdpVoiceStart = 402,
    /// <summary>
    /// 结束语音
    /// </summary>
    [pbr::OriginalName("UDP_VOICE_END")] UdpVoiceEnd = 403,
  }

  #endregion

}

#endregion Designer generated code
